language: node_js
node_js:
- '11'
- '10'
- '8'

cache:
  directories:
  - node_modules

script:
- yarn build
- yarn test
- yarn lint
- yarn test-gen
- yarn test-gen-cs
- yarn test-gen-env
- yarn check

deploy:
  provider: npm
  email: $NPM_AUTH_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    node_js: '8'
  skip_cleanup: true
